title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings

# Comment out theme since we're using remote_theme
#theme: minima

# Use remote_theme for GitHub Pages
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic

  # If you want to link only specific pages in the site-navigation, use this and list
  # the `path` property (as represented via Liquid) of the pages in the order they should
  # be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%b %-d, %Y"

  # Social Media Links
  # Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #
  # Entry keys:
  # * platform Platform name.
  # * user_url Full URL of social profile.
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/minima" }
    # - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
